imagePullSecrets: 
  - harbor-auth
image:
  repository: harbor.haijun.com/course/devops-demo
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  path: /
  hosts:
    - devops-demo.haijun.com

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 128Mi
